name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # Decode Miegir.snk
      - name: Decode Miegir.snk
        env:
          MIEGIR_SNK: ${{ secrets.MIEGIR_SNK }}
        run: |
          echo $MIEGIR_SNK | base64 --decode > Miegir.snk

      # Build and pack
      - name: Build solution and generate NuGet package
        run: dotnet pack -p:Configuration=Release -p:ContinuousIntegrationBuild=true -p:SignAssembly=true -p:AssemblyOriginatorKeyFile="$PWD/Miegir.snk"

      # Push to NuGet
      - name: Push generated package to NuGet
        run: dotnet nuget push "**/Miegir*.nupkg" --skip-duplicate -s nuget.org -k ${{ secrets.NUGET_AUTH_TOKEN }}
